version: 2.1

workflows:
  version: 2
  test-deploy:
    jobs:
      - run_test
      - dev_build:
          requires:
            - run_test
          filters:
            branches:
              ignore:
                - master
      - pro_build:
          requires:
            - run_test
          filters:
            branches:
              only:
                - master

jobs:
  working_directory: /tmp
  run_test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Instal libs
          command: npm install
      - run:
          name: Run test
          command: npm run test

  dev_build:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install libs
          command: npm install
      - run:
          name: Build extension
          command: npm run build      
  pro_build:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Install libs
          command: npm install
      - run: 
          name: Build project
          command: npm run build
      - store_artifacts:
        path: /tmp/build
        destination: "https://console.cloud.google.com/storage/browser/chrome-extension-production;tab=objects?forceOnBucketsSortingFiltering=false&hl=ja&project=ctca-pitwall&prefix=&forceOnObjectsSortingFiltering=false ( https://console.cloud.google.com/storage/browser/chrome-extension-production;tab=objects?forceOnBucketsSortingFiltering=false&amp;hl=ja&amp;project=ctca-pitwall&amp;prefix=&amp;forceOnObjectsSortingFiltering=false)"
       



